1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)
arr3 = arr1 + arr2
print(arr1)
print(arr2)
print(arr3)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


2. Write a Python Program to Multiply Two Matrices?

In [4]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(3,2)
arr3 = np.dot(arr1, arr2)
print(arr1)
print(arr2)
print(arr3)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 28  31]
 [100 112]]


3. Write a Python Program to Transpose a Matrix?

In [5]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.transpose(arr1)
print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
my_str = 'Hello! welcome to the world of python'

words = [word.lower() for word in my_str.split()]
words.sort()

for word in words:
    print(word)



hello!
of
python
the
to
welcome
world


5. Write a Python Program to Remove Punctuation From a String?

In [8]:
import re
 
test_str = "Python is the simple, easy, fantastic! to @learn"
 
print("The original string is : " + test_str)
 
res = re.sub(r'[^\w\s]', '', test_str)

print("The string after punctuation filter : " + res)

The original string is : Python is the simple, easy, fantastic! to @learn
The string after punctuation filter : Python is the simple easy fantastic to learn
